### PR TITLE
ios/videotoolbox: add function to support HEVC.

### PR DESCRIPTION
**Pull request by chodison**
fixed to support HEVC for ios videotoolbox.

### CODE REVIEW

**Comment by chodison** [comment]
fixed #2900

**Comment by chodison** [comment]
#3695

**Comment by chodison** [comment]
#3633

**Comment by Android4MediaPlayer** [comment]
@raymond1012 @bbcallen 我单独merge测试了

**Comment by Android4MediaPlayer** [comment]
@raymond1012 能更新下代码么

**Comment by raymond1012** [comment]
will support hevc in next version

**Comment by Android4MediaPlayer** [comment]
@raymond1012 merged?

**Comment by Android4MediaPlayer** [comment]
更新没有拉取到

**Pull request closed without merging**
