### PR TITLE
Native playback rate change

### PR DESCRIPTION
**Pull request by ChadCSong**
Add native code of set player‘s playback rate, Based on ffplay filter support.

### CODE REVIEW

**Comment by bbcallen** [comment]
ff_set_playback_rate() is not a completed feature, which should not be exported on master.

**Comment by ChadCSong** [comment]
Alright , I see.

**Comment by martji** [comment]
@ChadCSong I pull your code and compile successfully, but the example demo can not play, any help?

**Comment by ChadCSong** [comment]
@martji Any exceptions?

**Pull request closed without merging**
