### PR TITLE
fix HEVC in mkv

### PR DESCRIPTION
**Pull request by yuazhen**
Determine whether it need to generate VPS, SPS and PPS are based on extradata [1] instead extradata [0].
This patch can solve issue #923 and #1095 
sample mkv is http://trailers.divx.com/hevc/TearsOfSteelFull12min_1080p_24fps_27qp_1474kbps_GPSNR_42.29_HM11.mkv

### CODE REVIEW

**Comment by Android4MediaPlayer** [comment]
why？

**Comment by bbcallen** [comment]
I don't think it's more correct to check extra[1] only.
http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavcodec/hevc.c;h=b478065db2b8da7c41adcb7a1cdfc5139377c3a1;hb=HEAD#l3251

What's your opinion?
@yuazhen

**Comment by yuazhen** [comment]
Hi @bbcallen , I think you're right. But I didn't find the relevant docs about it.
Anyway, I modified the codes according to FFmpeg.

**Comment by bbcallen** [comment]
https://lists.matroska.org/pipermail/matroska-devel/2013-September/004567.html
There are some more references in this archive.

**Comment by bbcallen** [comment]
Merged.
Thanks.

**Pull request closed without merging**
