### PR TITLE
A little change

### PR DESCRIPTION
**Pull request by shingwasix**
Use NSFoundationVersionNumber instead of macro which compare system version.

### CODE REVIEW

**Comment by bbcallen** [comment]
Why? I don't think NSFoundationVersionNumber is more safe.

NSProcessInfo.operatingSystemVersion should be the best choice, if iOS7 is abandoned

**Comment by shingwasix** [comment]
I just think this code has a higher readability.
I don't know why did you think `NSFoundationVersionNumber` is not safe enough.

**Comment by bbcallen** [comment]
Comparing floats for equality is evil, including current macro style.

It doesn't make any sense to fix wrong code in another path.

**Comment by bbcallen** [comment]
Feel free to reopen this, if you have more comments.

**Pull request closed without merging**
