### PR TITLE
FFMpeg: Disable ASM on x86 builds

### PR DESCRIPTION
**Pull request by rooque**
This "fix" text relocations on targetSDK 23.

* Tested on emulator (sdk_google_phone_x86-userdebug 6.0 MASTER 2524533 test-keys) 

Signed-off-by: Victor Roque <victor.rooque@gmail.com>

### CODE REVIEW

**Comment by rooque** [comment]
Fix https://github.com/Bilibili/ijkplayer/issues/709

**Comment by bbcallen** [comment]
I don't think there are any real x86_32 devices can upgrade to android 6.0

**Comment by rooque** [comment]
You might be right, but x86 libs also can be used for x86-64 devices. And
shipping apk with both native libs means bigger apk and more space on disk.
I didn't saw any significant performance loss. I think devs can choose
between space/size or better performance.
Em 23 de fev de 2016 11:36 PM, "bbcallen" <notifications@github.com>
escreveu:

**Comment by bbcallen** [comment]
It has nothing to do with right or wrong.
It's only something about which solution I would like to maintain for my own application.

Maybe x86_64 is not much faster than x86_32, but x86 with asm is definitely faster than x86 without asm on old atom devices.
IMO, If you don't care about old atom devices, don't bother to support x86_32 at all.

**Comment by Saren-Arterius** [comment]
Text relocations still present if ffmpeg is compiled with openssl even with `--disable-asm` flag on x86 arch.

**Comment by xinzhengzhang** [comment]
@Saren-Arterius 
https://github.com/Bilibili/ijkplayer/commit/956758f222521f0d08a8a731dbaabb545251c2aa

**Comment by Saren-Arterius** [comment]
I am aware of this patch.

Snorlax <notifications@github.com> 於 2016年12月1日 週四 18:13 寫道：

**Pull request closed without merging**
