### PR TITLE
add libsoxr for android, can be compiled into ffmpeg

### PR DESCRIPTION
**Pull request by yuazhen**
the audio quality on a generic android device is poor:
~Android is to use a fixed sampling rate in its audio hardware layer. AudioFlinger will automatically performs resampling to handle different sample rates from the HW layer of PCM data sent by AudioTrack.
~because of the AudioResampler implementation in AudioFlinger, the response of the high frequency part is poor, even by adjusting AudioResampler using high-quality algorithm is not much improved.
~the default resampler in ffmpeg is SWR, It is also not so good.
in the case of Android's fixed sampling rate, the general method to enhance the audio quality is perform a high-quality resampling in application, then send the re-sampled PCMs to AudioFlinger. In ijkplayer, this can be done by using libsoxr within ffmpeg.
so we have this patch:
1. pull the libsoxr from http://git.code.sf.net/p/soxr/code
2. pull the android.toolchain.cmake from https://github.com/taka-no-me/android-cmake.git
3. add libsoxr compiling script
4. enable libsoxr in ffmpeg

### CODE REVIEW

**Comment by yuazhen** [comment]
how to use:
1. enable avfilter by remove CONFIG_AVFILTER define in ijkmedia/ijkplayer/config.h
2. call "ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "af", "aresample=resampler=soxr:osr=48000");"
48000 need to be changed according to hw sample rate.

**Comment by bbcallen** [comment]
Merged.
Thanks.

BTW:
The build of ffmpeg-arm64 and ffmpeg-x64_64 with libsoxr on MacOSX fails
Can you reproduce this issue?

```
====================
[*] check env arm64
====================
FF_ARCH=arm64
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Darwin x86_64
ANDROID_NDK=....
NDKr10e(64-bit) detected

--------------------
[*] check ffmpeg env
--------------------
libsoxr detected

--------------------
[*] configurate ffmpeg
--------------------
..../ijkplayer/android/contrib/build/ffmpeg-arm64/toolchain/bin//aarch64-linux-android-gcc
aarch64-linux-android-gcc is unable to create an executable file.
C compiler test failed.
```

With this line in config.log
```
 incompatible ..../ijkplayer/android/contrib/build/libsoxr-arm64/output/lib/libsoxr.a when searching for -lsoxr
```

**Comment by yuazhen** [comment]
It's my mistake that missing ABI config in the cmake statement and it has been fixed by my last commit.
Also, I found that soxr 0.1.2 is not compatible with 64bit target and the latest soxr codes could not compiled for armv5 because of the missing of arm_neon.h. So, using different commit base for 32bit and 64bit targets for compatibility.

**Comment by bbcallen** [comment]
Which one is better for armv7a and x86?

**Comment by yuazhen** [comment]
the 0.1.2 is tested on armv7a and the latest is not tested yet. So, I think maybe 0.1.2 is a better option.

**Comment by bbcallen** [comment]
Another error for arm64 and x86_64
```
[*] configurate libsoxr
--------------------
cmake -DCMAKE_TOOLCHAIN_FILE=....../ijkplayer/android/contrib/libsoxr-arm64/android.toolchain.cmake -DANDROID_NDK=....../NDK -DBUILD_EXAMPLES=0 -DBUILD_LSR_TESTS=0 -DBUILD_SHARED_LIBS=0 -DBUILD_TESTS=0 -DCMAKE_BUILD_TYPE=Release -DWITH_LSR_BINDINGS=0 -DWITH_OPENMP=0 -DWITH_PFFFT=0 -DANDROID_ABI=arm64-v8a -DCMAKE_INSTALL_PREFIX=....../ijkplayer/android/contrib/build/libsoxr-arm64/output
-- Could NOT find SIMD32 (missing:  SIMD32_C_FLAGS SIMD32_C_FLAGS) 
-- Could NOT find SIMD64 (missing:  SIMD64_C_FLAGS SIMD64_C_FLAGS) 
-- Check if the system is big endian
-- Searching 16 bit integer
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/TestBigEndian.cmake:51 (message):
  no suitable type found
Call Stack (most recent call first):
  CMakeLists.txt:149 (test_big_endian)
```

**Comment by bbcallen** [comment]
Works now. I didn't clean the build directory.

**Comment by bbcallen** [comment]
Merged.
Thanks.

**Pull request closed without merging**
